CREATE SCHEMA IF NOT EXISTS hackerrank;
USE hackerrank;

CREATE TABLE IF NOT EXISTS OCCUPATIONS(
	Name CHAR(100) NOT NULL,
    Occupation CHAR(100) NOT NULL);
INSERT INTO OCCUPATIONS VALUES ('Samantha', 'Doctor');
INSERT INTO OCCUPATIONS VALUES ('Julia', 'Actor');
INSERT INTO OCCUPATIONS VALUES ('Maria', 'Actor');
INSERT INTO OCCUPATIONS VALUES ('Meera', 'Singer');
INSERT INTO OCCUPATIONS VALUES ('Ashely', 'Professor');
INSERT INTO OCCUPATIONS VALUES ('Jane', 'Actor');
INSERT INTO OCCUPATIONS VALUES ('Jenny', 'Doctor');
INSERT INTO OCCUPATIONS VALUES ('Priya', 'Singer');

SELECT * FROM OCCUPATIONS;