CREATE SCHEMA IF NOT EXISTS hackerrank;
USE hackerrank;

CREATE TABLE IF NOT EXISTS BST_1(
	N INT,
    P INT);
INSERT INTO BST_1 VALUES (1, 2);
INSERT INTO BST_1 VALUES (3, 2);
INSERT INTO BST_1 VALUES (6, 8);
INSERT INTO BST_1 VALUES (9, 8);
INSERT INTO BST_1 VALUES (2, 5);
INSERT INTO BST_1 VALUES (8, 5);
INSERT INTO BST_1 VALUES (5, NULL);

SELECT * FROM BST_1;